export const supabaseUrl = "https://abfijmfytfxbjoqjesya.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZmlqbWZ5dGZ4YmpvcWplc3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc1MjkzNzEsImV4cCI6MjA0MzEwNTM3MX0.33FmawLi5pg17ACD2r6HiTEOKbNyRZmbv7E6moX7W8A";
